version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: bundler
    directory: /gemfiles/runtime
    schedule:
      interval: weekly
  - package-ecosystem: bundler
    directory: /gemfiles/release
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
