# frozen_string_literal: true

require "bundler"

root = File.expand_path("..", __dir__)
gemfile_path = ARGV.fetch(0, File.join(root, "gemfiles/release/Gemfile"))
lockfile_path = ARGV.fetch(1, File.join(root, "gemfiles/release/Gemfile.lock"))

expected_gemfile = <<~GEMFILE
  source "https://rubygems.org"

  gem "sigstore-cli", "= 0.2.3"
GEMFILE

unless File.binread(gemfile_path) == expected_gemfile
  abort "release Gemfile must contain only the pinned sigstore-cli dependency from RubyGems.org"
end

lockfile = File.binread(lockfile_path)
lock = Bundler::LockfileParser.new(lockfile)
source = lock.sources.first

valid_source = lock.sources.one? &&
  source.is_a?(Bundler::Source::Rubygems) &&
  source.remotes.map(&:to_s) == [ "https://rubygems.org/" ] &&
  lock.specs.all? { |spec| spec.source == source }
abort "release lockfile must use only https://rubygems.org/" unless valid_source

dependency = lock.dependencies["sigstore-cli"]
valid_dependency = lock.dependencies.one? &&
  dependency&.requirement&.to_s == "= 0.2.3" &&
  lock.specs.any? { |spec| spec.name == "sigstore-cli" && spec.version.to_s == "0.2.3" }
abort "release lockfile must pin sigstore-cli 0.2.3 as its only direct dependency" unless valid_dependency

sections = Hash.new { |hash, key| hash[key] = [] }
section = nil
lockfile.each_line do |line|
  if line.match?(/\A[A-Z][A-Z ]*\n?\z/)
    section = line.strip
  elsif section
    sections[section] << line
  end
end

unless sections["BUNDLED WITH"] == [ "  4.0.6\n" ]
  abort "release lockfile must be generated by Bundler 4.0.6"
end

checksums = {}
sections.fetch("CHECKSUMS") { abort "release lockfile has no CHECKSUMS section" }.each do |line|
  next if line.strip.empty?

  match = line.match(/\A  (?<spec>.+ \([^)]+\)) sha256=(?<digest>[0-9a-f]{64})\n?\z/)
  abort "invalid release checksum entry: #{line.inspect}" unless match
  abort "duplicate release checksum for #{match[:spec]}" if checksums.key?(match[:spec])

  checksums[match[:spec]] = match[:digest]
end

locked_specs = lock.specs.map(&:lock_name)
abort "duplicate specs in release lockfile" unless locked_specs.uniq.size == locked_specs.size

missing = locked_specs - checksums.keys
extra = checksums.keys - locked_specs
unless missing.empty? && extra.empty?
  abort "release checksum coverage mismatch (missing: #{missing.join(", ")}; extra: #{extra.join(", ")})"
end

puts "Verified #{locked_specs.size} checksummed release-toolchain gems from RubyGems.org"
